trigger:
- main

pool:
  name: 'pool1'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    restoreArguments: '--configuration $(build.configuration)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(build.configuration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(build.configuration)'
