trigger:
- main

pool:
  name: 'pool1'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    

    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/devopswebapp.csproj'
        includeNuGetOrg: false
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/devopswebapp.csproj'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/devopswebapp.csproj'
        publishTestResults: true
    
    