trigger:
- main

pool:
  name: 'pool1'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'devopswebapp.csproj'
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'devopswebapp.csproj'
    arguments: '--configuration $(build.configuration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'devopswebapp.csproj'
    arguments: '--configuration $(build.configuration)'
