# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'pool2'

variables:
  buildconfiguration: 'Debug'

stages:
  - stage: 
    jobs:
    - job: 
      steps:
      - task: UseDotNet@2
        displayName: 'DotNet installed'
        inputs:
          packageType: 'sdk'
          version: '8.x'
      
      - task: DotNetCoreCLI@2
        displayName: 'restored'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          arguments: '-C $(buildconfiguration)'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '-C $(buildconfiguration)'


